CREATE TABLE IF NOT EXISTS member (
    id           INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name         VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS sessions (
    id           INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    sesson_data    TEXT
);


CREATE TABLE IF NOT EXISTS entry(
 entry_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
 body VARCHAR(255) NOT NULL
);





